# Generated by Django 4.1.3 on 2022-12-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column2', models.IntegerField(blank=True, max_length=30, null=True, verbose_name='Unnamed: 0.1')),
                ('column3', models.CharField(blank=True, max_length=30, null=True, verbose_name='Unnamed: 0')),
                ('name', models.BooleanField(blank=True, max_length=100, null=True, verbose_name='pname')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('store', models.CharField(blank=True, max_length=100, null=True)),
                ('pcode', models.IntegerField(blank=True, max_length=20, null=True)),
                ('ru_pname', models.CharField(blank=True, max_length=200, null=True)),
                ('en_pname', models.CharField(blank=True, max_length=200, null=True)),
                ('conames', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Product List',
                'verbose_name_plural': 'Product Lists',
                'ordering': ['-name'],
            },
        ),
    ]
