# Generated by Django 4.1.3 on 2022-12-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttable',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='pname'),
        ),
    ]
