# Generated by Django 4.1.3 on 2022-12-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchAPI', '0002_alter_producttable_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttable',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
