# Generated by Django 4.1.3 on 2022-12-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchAPI', '0003_alter_producttable_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttable',
            name='column3',
            field=models.IntegerField(blank=True, max_length=30, null=True, verbose_name='Unnamed: 0'),
        ),
    ]
